service: demo-app
image: badri/demo-app
ssh:
  user: kamal
builder:
  arch: amd64
servers:
  web:
    hosts:
    - $DEST_VM_HOST
proxy:
  ssl: true
  host: demo-app.vmkit.app
  app_port: 8000
registry:
  server: ghcr.io
  username: vmkit-deploy[bot]
  password:
  - KAMAL_REGISTRY_PASSWORD
